<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERPDetektiv.Application\ERPDetektiv.Application.csproj" />
    <ProjectReference Include="..\ERPDetektiv.Core\ERPDetektiv.Core.csproj" />
  </ItemGroup>
</Project>
